# Generated by Django 5.0.7 on 2025-08-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracteddata',
            old_name='extracted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='certificate_no',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='extra_json',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='heat_no',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='plate_no',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='status',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='field_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='field_value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extractor.vendor'),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.uploadedpdf'),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
