# Generated by Django 5.2.5 on 2025-08-25 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_rename_extracted_at_extracteddata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='field_value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='extractor.uploadedpdf'),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='extractor.vendor'),
            preserve_default=False,
        ),
    ]
