# Generated by Django 5.2.5 on 2025-08-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_alter_extracteddata_field_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracteddata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Extracted Data', 'verbose_name_plural': 'Extracted Data'},
        ),
        migrations.AlterModelOptions(
            name='uploadedpdf',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Uploaded PDF', 'verbose_name_plural': 'Uploaded PDFs'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
    ]
