# Generated by Django 5.0.7 on 2025-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_alter_extracteddata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
